import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // Manual sidebar structure
  tutorialSidebar: [
    'intro',
    'module-1-robotic-nervous-system/index', // Module 1: Single page, direct link
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        'module-2-digital-twin/index', // Main module page
        'module-2-digital-twin/sensors', // Sub-page
      ],
    },
    'module-3-ai-robot-brain/index', // Module 3: Single page, direct link
    'module-4-vla-capstone/index', // Module 4: Single page, direct link
    'hardware-lab/index', // Hardware Lab: Single page, direct link
  ],
};

export default sidebars;
